name: jupedsim-windows

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '5 0 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cloning jpscore
      uses: actions/checkout@v3
      with:
        repository: jupedsim/jpscore
        ref: SUMO-Integration
        path: jpscore

    - name: Building jpscore dependencies
      run:  |
        mkdir jpscore-deps
        cd jpscore
        vcpkg.exe --x-install-root=../jpscore-deps --triplet=x64-windows install
        Compress-Archive -Path ../jpscore-deps -DestinationPath ../jpscore-deps.zip

    - name: Uploading dependency artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deps
        path: jpscore-deps.zip

    - name: Building jpscore
      shell: cmd
      run: |
        mkdir jpscore-build
        mkdir jpscore-install
        cd jpscore-build
        cmake -DCMAKE_PREFIX_PATH=%CD%/../jpscore-deps/x64-windows -DCMAKE_INSTALL_PREFIX=%CD%/../jpscore-install -DBUILD_JPSVIS=OFF ../jpscore
        cmake --build . --config Release
        cmake --install . --config Release

    - name: Uploading release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jpscore-release
        path: jpscore-install

    - name: Building jpscore debug
      shell: cmd
      run: |
        mkdir jpscore-build-debug
        mkdir jpscore-install-debug
        cd jpscore-build-debug
        cmake -DCMAKE_PREFIX_PATH=%CD%/../jpscore-deps/x64-windows -DCMAKE_INSTALL_PREFIX=%CD%/../jpscore-install-debug -DBUILD_JPSVIS=OFF ../jpscore
        cmake --build . --config Debug
        cmake --install . --config Debug

    - name: Uploading debug artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jpscore-debug
        path: jpscore-install-debug

    - name: Cloning SUMO
      uses: actions/checkout@v3
      with:
        path: sumo
        fetch-depth: 0
 
    - name: Fetching SUMO tags
      run: |
        cd sumo
        git fetch --tags --force

    - name: Cloning SUMO Libraries
      uses: actions/checkout@v3
      with:
        repository: DLR-TS/SUMOLibraries 
        path: sumolibraries

    - name: Configuring and building SUMO
      shell: cmd
      run: |
        cd sumo
        mkdir build_msvc
        cd build_msvc
        cmake -DJUPEDSIM_DIR=%CD%/../../jpscore-install ..
        cmake --build . --config Release

    - name: Building Examples and Tests
      run: |
        cd sumo/build_msvc
        cmake --build . --target examples
        ctest --output-on-failure
