name: jupedsim-windows

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '5 0 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cloning jpscore
      uses: actions/checkout@v3
      with:
        repository: jupedsim/jpscore
        ref: SUMO-Integration
        path: jpscore

    - name: Building jpscore dependencies
      run:  |
        mkdir jpscore-deps
        cd jpscore
        vcpkg.exe --x-install-root=../jpscore-deps --triplet=x64-windows-static install

    - name: Uploading dependency artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jpscore-deps
        path: jpscore-deps

    - name: Building jpscore
      run: |
        mkdir jpscore-build
        mkdir jpscore-install
        cd jpscore-build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$PWD/../jpscore-deps -DCMAKE_INSTALL_PREFIX=$PWD/../jpscore-install -DBUILD_JPSVIS=OFF ../jpscore
        cmake --build .
        cmake --install .

    - name: Cloning SUMO
      uses: actions/checkout@v3
      with:
        path: sumo
        fetch-depth: 0
 
    - name: Fetching SUMO tags
      run: |
        cd sumo
        git fetch --tags --force

    - name: Configuring and building SUMO
      run: |
        mkdir -p sumo/cmake-build 
        cd sumo/cmake-build 
        cmake -DJUPEDSIM_DIR=$PWD/../../jpscore-install ..
        cmake --build .

    - name: Building Examples and Tests
      run: |
        cd sumo/cmake-build
        cmake --build . --target examples
        ctest --output-on-failure
