name: linux-arm-wheels

on:
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
      - 'src/gui*/**'
      - 'src/netedit/**'
      - 'tests/netedit/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
  workflow_dispatch:
  schedule:
    - cron:  '5 1 * * *'

jobs:
  build-manylinux-arm-wheels:
    runs-on: macos-14

    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Building SUMO / libsumo Python wheels (latest manylinux docker)
      uses: docker://quay.io/pypa/manylinux2014_aarch64
      with:
        entrypoint: tools/build_config/build_wheels.sh

    - name: Uploading artifacts (Python wheels)
      uses: actions/upload-artifact@v4
      with:
        name: manylinux-arm-wheels
        path: wheelhouse

  ###################
  # publishing wheels
  ###################
  publish-wheels:
    if: github.repository == 'eclipse-sumo/sumo' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags'))
    needs: [build-manylinux-arm-wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Downloading Wheels artifact
      uses: actions/download-artifact@v4

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: manylinux-arm-wheels/
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: manylinux-wheels/
